#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = ["duckdb>=1.4,<2"]
# ///
"""Generate Sundae Run's key-free Southern California ice-cream directory."""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

import duckdb


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data" / "socal-ice-cream.js"
CATALOG_URL = "https://stac.overturemaps.org/catalog.json"
BOUNDS = {"west": -118.95, "north": 34.85, "east": -116.05, "south": 32.45}
CATEGORIES = ("ice_cream_shop", "frozen_yogurt_shop", "gelato_shop")


def latest_release() -> str:
    request = urllib.request.Request(CATALOG_URL, headers={"User-Agent": "SundaeRunDirectoryUpdater/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        catalog = json.load(response)
    for link in catalog.get("links", []):
        if link.get("latest") is True:
            match = re.search(r"/(\d{4}-\d{2}-\d{2}\.\d+)/catalog\.json$", link.get("href", ""))
            if match:
                return match.group(1)
    raise RuntimeError("Overture STAC catalog did not identify a latest release")


def fetch_places(release: str) -> list[dict]:
    path = f"s3://overturemaps-us-west-2/release/{release}/theme=places/type=place/*"
    con = duckdb.connect()
    con.execute("INSTALL httpfs; LOAD httpfs; SET s3_region='us-west-2';")
    rows = con.execute(
        f"""
        SELECT
          id,
          names.primary AS name,
          taxonomy.primary AS category,
          addresses[1].freeform AS address,
          addresses[1].locality AS locality,
          addresses[1].postcode AS postcode,
          bbox.xmin AS lng,
          bbox.ymin AS lat,
          confidence
        FROM read_parquet('{path}', filename=true, hive_partitioning=1)
        WHERE bbox.xmin BETWEEN ? AND ?
          AND bbox.ymin BETWEEN ? AND ?
          AND taxonomy.primary IN (?, ?, ?)
          AND names.primary IS NOT NULL
          AND confidence >= 0.70
        ORDER BY confidence DESC, name
        """,
        [
            BOUNDS["west"], BOUNDS["east"], BOUNDS["south"], BOUNDS["north"],
            *CATEGORIES,
        ],
    ).fetchall()

    seen: set[tuple[str, int, int]] = set()
    places: list[dict] = []
    for _, name, category, address, locality, postcode, lng, lat, confidence in rows:
        key = (name.casefold(), round(lat * 10_000), round(lng * 10_000))
        if key in seen:
            continue
        seen.add(key)
        places.append(
            {
                "name": name,
                "category": category,
                "address": address or "",
                "locality": locality or "",
                "postcode": postcode or "",
                "lat": round(float(lat), 6),
                "lng": round(float(lng), 6),
                "confidence": round(float(confidence), 3),
            }
        )
    return places


def main() -> None:
    release = latest_release()
    places = fetch_places(release)
    payload = {
        "source": "Overture Maps Places",
        "release": release,
        "bounds": BOUNDS,
        "count": len(places),
        "places": places,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "// Generated by scripts/update-socal-ice-cream.py; do not edit manually.\n"
        f"window.SOCAL_ICE_CREAM_DIRECTORY = {json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(places)} places from Overture {release} to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
